### PR TITLE
I'm having problems downloading pillow

### PR DESCRIPTION
**Pull request by mviruet2**
I don't know if my code runs or not. I have python 3.5 and I cant find
pillow for this version

### CODE REVIEW

**Comment by jondisla** [comment]
If you're using PC, goto your command prompt and type
pip install pillow

**Comment by jondisla** [comment]
same as you did with selenium...
pip install selenium

**Comment by halfaro1** [comment]
thanks for the tip @jondisla !
@mviruet2 : let us know if you're able to get it

**Comment by halfaro1** [comment]
@mviruet2 
Thanks for continuing to work on this project! Unfortunately, I have to grade this project as-is. I am closing out this pull request and entering your grade on Blackboard. Please see your grade there.

**Pull request closed without merging**
